-- Insert all the Egyptian training spaces and academies
INSERT INTO public.spaces (name, type, address, city, owner, description, images, equipment, capacity, price_per_hour, rating, coordinates, availability) VALUES 
-- Cairo (القاهرة)
('الأكاديمية الوطنية للعلوم و المهارات', 'classroom', 'القاهرة', 'القاهرة', 'الأكاديمية الوطنية للعلوم و المهارات', 'مؤسسة تدريب متخصصة في العلوم والمهارات التقنية', '{"https://drive.google.com/open?id=1UhIq4ApVvqZA1pdCASGKYbcyhXKihluK"}', '{"تدريب تقني", "مختبر علوم", "Wi-Fi"}', 25, 50.00, 4.5, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('International Little Coders', 'classroom', 'منصة أون لاين', 'القاهرة', 'International Little Coders', 'مؤسسة تدريب برمجة للأطفال عبر الإنترنت', '{"https://drive.google.com/open?id=1zJ_Kp6Ln8YhLt-dgwC2WGqgxTbOKXSES"}', '{"برمجة", "كمبيوتر", "Wi-Fi"}', 20, 40.00, 4.7, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], "hours": "10AM-8PM"}'),
('Robotics Education', 'makerspace', 'القاهرة', 'القاهرة', 'Robotics Education', 'مؤسسة تدريب متخصصة في تعليم الروبوتات', '{"https://drive.google.com/open?id=12aKi8FIi8PSWTYspPYGuAHvJ_dDnpWg2"}', '{"روبوتات", "مجموعات إلكترونية", "3D Printer"}', 15, 60.00, 4.8, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),
('مشكاة كيدز', 'classroom', 'القاهرة', 'القاهرة', 'مشكاة كيدز', 'مؤسسة تدريب للأطفال', '{"https://drive.google.com/open?id=12-xwtzbefQkw0vslhOhBXBOqBxSmoe1R"}', '{"تدريب أطفال", "ألعاب تعليمية", "Wi-Fi"}', 20, 35.00, 4.6, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('Robocode school', 'makerspace', 'القاهرة', 'القاهرة', 'Robocode school', 'مدرسة تعليم البرمجة والروبوتات', '{"https://drive.google.com/open?id=13NK5C9yiA1yZJ-tPTVjZPYWL_-Nw4OIx"}', '{"برمجة", "روبوتات", "كمبيوتر"}', 18, 55.00, 4.7, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),
('Techademics', 'classroom', 'القاهرة', 'القاهرة', 'Techademics', 'مؤسسة تدريب تقني وتنظيم مسابقات', '{"https://drive.google.com/open?id=1hPpHgSpmjN5okY0JjQSvV35VxhS5wMQY"}', '{"تدريب تقني", "مسابقات", "معدات"}', 25, 45.00, 4.5, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-8PM"}'),
('Mindvalley', 'classroom', 'القاهرة', 'القاهرة', 'Mindvalley', 'مؤسسة تدريب وتطوير المهارات', '{"https://drive.google.com/open?id=1knn0M7k0NYlzPlfFl2443Zhlna3ckead"}', '{"تطوير مهارات", "تدريب", "Wi-Fi"}', 30, 40.00, 4.4, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('Rawasy Misr International School', 'classroom', 'القاهرة', 'القاهرة', 'Rawasy Misr International School', 'مدرسة دولية تعليمية وتدريبية', '{"https://drive.google.com/open?id=1KtcMKNm9h-mIXuJtHmuXoin0CQZmOTxI"}', '{"تعليم دولي", "تدريب", "مختبرات"}', 35, 50.00, 4.6, '{"lat": 30.0444, "lng": 31.2357}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "8AM-3PM"}'),

-- Alexandria (الاسكندرية)
('Creative generation academy', 'makerspace', 'الاسكندرية', 'الاسكندرية', 'Creative generation academy', 'مؤسسة تدريب وتنظيم مسابقات إبداعية', '{"https://drive.google.com/open?id=1_qdyrQNxuqrGFpXOXw9tX0yksaAUawHQ"}', '{"إبداع", "مسابقات", "تصميم"}', 22, 45.00, 4.8, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),
('مدارس هارفست الدولية', 'classroom', 'الاسكندرية', 'الاسكندرية', 'مدارس هارفست الدولية', 'مؤسسة تعليمية وتدريبية دولية', '{"https://drive.google.com/open?id=15pXp0_jHPU4tEepbIOZL_ivXru9hfjeb"}', '{"تعليم دولي", "مختبرات", "Wi-Fi"}', 40, 55.00, 4.7, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "8AM-4PM"}'),
('Makers Electronics', 'coworking', 'الاسكندرية', 'الاسكندرية', 'Makers Electronics', 'مؤسسة توريد مستلزمات إلكترونية', '{"https://drive.google.com/open?id=17Cyaqjic81rrsjeeT6SYXA4Q2Q3pQYSm"}', '{"إلكترونيات", "مكونات", "أدوات"}', 15, 30.00, 4.5, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Saturday"], "hours": "9AM-8PM"}'),
('Robo Camp', 'makerspace', 'الاسكندرية', 'الاسكندرية', 'Robo Camp', 'مؤسسة تدريب روبوتات وتوريد مستلزمات', '{"https://drive.google.com/open?id=1jDYU4vk2NInJbMweHsIfi0j5UdG8sCXz"}', '{"روبوتات", "مستلزمات", "ورش عمل"}', 20, 50.00, 4.9, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-8PM"}'),
('لوكسفورد كلاسيز', 'classroom', 'الاسكندرية', 'الاسكندرية', 'لوكسفورد كلاسيز', 'مؤسسة تدريب تعليمية', '{"https://drive.google.com/open?id=1RkL9iEBaAGlrBwjmYlej4Wy6ePIw7dwE"}', '{"تدريب", "تعليم", "Wi-Fi"}', 25, 40.00, 4.6, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-7PM"}'),
('AcA Robotics', 'makerspace', 'الاسكندرية', 'الاسكندرية', 'AcA Robotics', 'أكاديمية تدريب الروبوتات المتقدمة', '{"https://drive.google.com/open?id=1vX-a2OB5NdGQScAEZ29CJ_5LSz2GJzpB"}', '{"روبوتات متقدمة", "AI", "برمجة"}', 18, 65.00, 4.8, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-8PM"}'),
('أطفال اليكس', 'classroom', 'الاسكندرية', 'الاسكندرية', 'أطفال اليكس', 'مؤسسة تدريب الأطفال', '{"https://drive.google.com/open?id=1xuHuND7dOjVtJDB97YO0vuJ3IUvrse8t"}', '{"تدريب أطفال", "أنشطة", "Wi-Fi"}', 25, 35.00, 4.5, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('Technospace', 'makerspace', 'الاسكندرية', 'الاسكندرية', 'Technospace', 'مؤسسة تدريب تقني وتنظيم مسابقات', '{"https://example.com/technospace.jpg"}', '{"تدريب تقني", "مسابقات", "معدات حديثة"}', 20, 55.00, 4.7, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-8PM"}'),
('Sparkminds', 'classroom', 'الإسكندرية', 'الإسكندرية', 'Sparkminds', 'مؤسسة تدريب إبداعية', '{"https://drive.google.com/open?id=1PCpTIVvsV87tjh4_c5O1lRWwsdF6QyP8"}', '{"إبداع", "ابتكار", "تفكير"}', 22, 42.00, 4.6, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),
('Pyramakerz', 'makerspace', 'الإسكندرية', 'الإسكندرية', 'Pyramakerz', 'مؤسسة تدريب وتوريد مستلزمات', '{"https://drive.google.com/open?id=13rGIw5WGAyjh7xw3WovxOZ6-LoARgjdZ"}', '{"صناعة", "مستلزمات", "ورش"}', 18, 48.00, 4.8, '{"lat": 31.2001, "lng": 29.9187}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-8PM"}'),

-- Giza (الجيزة)
('الأكاديمية الدولية للتدريب والابتكار', 'classroom', 'الجيزة', 'الجيزة', 'الأكاديمية الدولية للتدريب والابتكار', 'مؤسسة تدريب دولية وتنظيم مسابقات', '{"https://drive.google.com/open?id=1cZo9rkeedNsTpzlUtZeiYrQONJEtrvPS"}', '{"تدريب دولي", "ابتكار", "مسابقات"}', 30, 50.00, 4.7, '{"lat": 30.0131, "lng": 31.2089}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-7PM"}'),
('اكاديمية فانتازيا لتطوير الذات و التدريب التكنولوجى', 'classroom', 'الجيزة', 'الجيزة', 'اكاديمية فانتازيا', 'مؤسسة تدريب تطوير الذات والتكنولوجيا', '{"https://drive.google.com/open?id=1DSmsJXqfFMkESUzfJQ4jJCz0B7ahou-z"}', '{"تطوير ذات", "تكنولوجيا", "تدريب"}', 25, 45.00, 4.6, '{"lat": 30.0131, "lng": 31.2089}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),
('Little programmer Academy', 'classroom', 'الجيزة', 'الجيزة', 'Little programmer Academy', 'أكاديمية تعليم البرمجة للصغار', '{"https://drive.google.com/open?id=1qfG7FlFJbFNfAPi1XQ4YpeonyEZJML-X"}', '{"برمجة", "أطفال", "كمبيوتر"}', 20, 40.00, 4.8, '{"lat": 30.0131, "lng": 31.2089}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-6PM"}'),
('المخترع الصغير للمنتجات التعليمية', 'classroom', 'الجيزة', 'الجيزة', 'المخترع الصغير', 'مؤسسة تدريب وتوريد منتجات تعليمية', '{"https://drive.google.com/open?id=1ucnWp09v22hH-B-7EoCD6BoygRJcNvER"}', '{"اختراع", "منتجات تعليمية", "ابتكار"}', 22, 38.00, 4.5, '{"lat": 30.0131, "lng": 31.2089}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('Little Coder Academy', 'classroom', 'الجيزة', 'الجيزة', 'Little Coder Academy', 'أكاديمية تعليم البرمجة', '{"https://drive.google.com/open?id=1xmuBkNv8x6jPHeklOr7VllasTssr7J9-"}', '{"برمجة", "كودينغ", "تعليم"}', 18, 42.00, 4.7, '{"lat": 30.0131, "lng": 31.2089}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),

-- Other Cities
('ابيكس للبرمجة وتعليم علوم الكمبيوتر', 'classroom', 'الأقصر', 'الأقصر', 'ابيكس', 'مؤسسة تدريب برمجة وعلوم كمبيوتر', '{"https://drive.google.com/open?id=1luyZHqO1Zi9jIkygaq40yRjtmTHCWpJw"}', '{"برمجة", "علوم كمبيوتر", "مسابقات"}', 20, 35.00, 4.5, '{"lat": 25.6872, "lng": 32.6396}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-6PM"}'),
('Science academy', 'classroom', 'البحيرة كوم حمادة', 'البحيرة', 'Science academy', 'أكاديمية العلوم للتدريب', '{"https://drive.google.com/open?id=1rZLtBbbY5gtJRVdvEdfoPoRh6nFqOOUx"}', '{"علوم", "تجارب", "مختبر"}', 25, 30.00, 4.4, '{"lat": 30.9876, "lng": 30.3433}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('الخبير', 'classroom', 'البحيره', 'البحيرة', 'الخبير', 'مؤسسة تدريب متخصصة', '{"https://drive.google.com/open?id=1pC9NqOi3zgrIlovRvp9nGt5QASMXgUQ5"}', '{"تدريب متخصص", "خبرة", "مهارات"}', 20, 32.00, 4.3, '{"lat": 30.9876, "lng": 30.3433}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-6PM"}'),
('Algo Coder Academy', 'classroom', 'الشرقية', 'الشرقية', 'Algo Coder Academy', 'أكاديمية تعليم الخوارزميات والبرمجة', '{"https://drive.google.com/open?id=1a1rfhdgT1A8egFuzEKAaex4QHtUfSJqO"}', '{"خوارزميات", "برمجة", "منطق"}', 18, 40.00, 4.6, '{"lat": 30.5965, "lng": 31.5041}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}'),
('Bright Brains Academy', 'classroom', 'العاشر من رمضان', 'الشرقية', 'Bright Brains Academy', 'أكاديمية العقول المشرقة', '{"https://drive.google.com/open?id=1yHQKbNKRZpufEls98cN5LM5GEe7cBOcF"}', '{"ذكاء", "تفكير", "تطوير"}', 22, 38.00, 4.5, '{"lat": 30.3397, "lng": 31.7251}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-6PM"}'),
('سكوبو أكاديمي', 'classroom', 'الغربية', 'الغربية', 'سكوبو أكاديمي', 'أكاديمية تدريب شاملة', '{"https://drive.google.com/open?id=1WYMb_wGSBGkTXMiF8qeSXgw7KVEID9NJ"}', '{"تدريب شامل", "مهارات", "تطوير"}', 25, 35.00, 4.4, '{"lat": 30.7618, "lng": 31.0335}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "9AM-7PM"}'),
('ICanCode Academy', 'classroom', 'الغربيه', 'الغربية', 'ICanCode Academy', 'أكاديمية تعليم البرمجة للجميع', '{"https://drive.google.com/open?id=1ZVTg3eNs-KSrdDUc0_Wgdk2bd98vsdyf"}', '{"برمجة للجميع", "تعليم", "كودينغ"}', 20, 42.00, 4.7, '{"lat": 30.7618, "lng": 31.0335}', '{"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], "hours": "10AM-7PM"}');