// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyzyexfkivhhhfcggeif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5enlleGZraXZoaGhmY2dnZWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTA4NDgsImV4cCI6MjA3MjcyNjg0OH0.weu6fUdhPi4cIGyda1OB_cPiMVD2JxO6Rq1IFs4ZnoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});